version: '3.8'
services:
  word-count:
    container_name: hymaia
    restart: always
    build: .
    ports:
      - 8080:8080
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - word-count
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 